import type { ConvertedTrack } from '../types'

// Standard tunings: high string first (top of tab to bottom, as written)
const GUITAR_LABELS = ['e', 'B', 'G', 'D', 'A', 'E']
const GUITAR_OPEN = [64, 59, 55, 50, 45, 40]

const BASS_4_LABELS = ['G', 'D', 'A', 'E']
const BASS_4_OPEN = [43, 38, 33, 28]

const BASS_5_LABELS = ['G', 'D', 'A', 'E', 'B']
const BASS_5_OPEN = [43, 38, 33, 28, 23]

// GM drum pitches with their ASCII tab labels
const DRUM_ROWS: Array<{ label: string; pitch: number }> = [
  { label: 'CC', pitch: 49 }, // Crash cymbal
  { label: 'RC', pitch: 51 }, // Ride cymbal
  { label: 'OH', pitch: 46 }, // Hi-hat open
  { label: 'HH', pitch: 42 }, // Hi-hat closed
  { label: 'T1', pitch: 48 }, // High tom
  { label: 'T2', pitch: 47 }, // Mid tom
  { label: 'FT', pitch: 41 }, // Floor tom
  { label: 'SN', pitch: 38 }, // Snare
  { label: 'BD', pitch: 36 } // Bass drum
]

function makeHeader(
  name: string,
  bpm: number,
  timeSignature: { numerator: number; denominator: number },
  tuningStr: string
): string {
  return [
    `Song: ${name}`,
    `BPM: ${bpm}`,
    `Time Signature: ${timeSignature.numerator}/${timeSignature.denominator}`,
    `Tuning: ${tuningStr}`,
    'Generated by Tab to Backing Track',
    'github.com/hakai197/tabtobackingtrack',
    '=====================================',
    ''
  ].join('\n')
}

function buildInstrumentTab(
  track: ConvertedTrack,
  bpm: number,
  timeSignature: { numerator: number; denominator: number }
): string {
  let labels: string[]
  let openMidi: number[]

  if (track.type === 'guitar') {
    labels = GUITAR_LABELS
    openMidi = GUITAR_OPEN
  } else {
    const lowestPitch = track.notes.length > 0 ? Math.min(...track.notes.map((n) => n.pitch)) : 28
    if (lowestPitch < 28) {
      labels = BASS_5_LABELS
      openMidi = BASS_5_OPEN
    } else {
      labels = BASS_4_LABELS
      openMidi = BASS_4_OPEN
    }
  }

  const SIXTEENTH = 60 / bpm / 4
  const colsPerBar = timeSignature.numerator * 4

  // Build note grid: grid[stringIdx] = Map<column, fret>
  const grid: Map<number, number>[] = openMidi.map(() => new Map<number, number>())

  for (const note of track.notes) {
    const col = Math.round(note.startTime / SIXTEENTH)
    let bestFret = Infinity
    let bestString = -1
    for (let si = 0; si < openMidi.length; si++) {
      const fret = note.pitch - openMidi[si]!
      if (fret >= 0 && fret <= 24 && fret < bestFret && !grid[si]!.has(col)) {
        bestFret = fret
        bestString = si
      }
    }
    if (bestString >= 0) {
      grid[bestString]!.set(col, bestFret)
    }
  }

  // Round up maxCol to the nearest bar boundary
  const maxColRaw =
    track.notes.length > 0
      ? Math.ceil(Math.max(...track.notes.map((n) => n.startTime + n.duration)) / SIXTEENTH)
      : colsPerBar * 4
  const numBars = Math.ceil(maxColRaw / colsPerBar) + 1
  const maxCol = numBars * colsPerBar

  // Column widths: 2 chars if any fret in that column is >= 10, else 1
  const colWidths: number[] = new Array(maxCol).fill(1)
  for (let si = 0; si < openMidi.length; si++) {
    for (const [col, fret] of grid[si]!) {
      if (fret >= 10 && col < maxCol) colWidths[col] = 2
    }
  }

  // Bar widths in characters (content + trailing '|')
  const barWidths: number[] = []
  for (let bar = 0; bar < numBars; bar++) {
    let w = 1
    for (let beat = 0; beat < colsPerBar; beat++) {
      w += colWidths[bar * colsPerBar + beat] ?? 1
    }
    barWidths.push(w)
  }

  // Group bars into rows targeting ~60 content chars per row
  const ROW_TARGET = 60
  const rowGroups: number[][] = []
  let currentGroup: number[] = []
  let currentWidth = 0

  for (let bar = 0; bar < numBars; bar++) {
    const bw = barWidths[bar] ?? 0
    if (currentGroup.length > 0 && currentWidth + bw > ROW_TARGET) {
      rowGroups.push(currentGroup)
      currentGroup = [bar]
      currentWidth = bw
    } else {
      currentGroup.push(bar)
      currentWidth += bw
    }
  }
  if (currentGroup.length > 0) rowGroups.push(currentGroup)

  const tuningStr = [...labels].reverse().join(' ')
  const outputLines: string[] = [makeHeader(track.name, bpm, timeSignature, tuningStr)]

  for (const barIndices of rowGroups) {
    for (let si = 0; si < labels.length; si++) {
      let line = `${labels[si]}|`
      for (const bar of barIndices) {
        for (let beat = 0; beat < colsPerBar; beat++) {
          const col = bar * colsPerBar + beat
          const width = colWidths[col] ?? 1
          const fret = grid[si]?.get(col)
          if (fret !== undefined) {
            line += String(fret).padEnd(width, '-')
          } else {
            line += '-'.repeat(width)
          }
        }
        line += '|'
      }
      outputLines.push(line)
    }
    outputLines.push('')
  }

  return outputLines.join('\n')
}

function buildDrumTab(
  track: ConvertedTrack,
  bpm: number,
  timeSignature: { numerator: number; denominator: number }
): string {
  const SIXTEENTH = 60 / bpm / 4
  const colsPerBar = timeSignature.numerator * 4

  const drumHits = new Map<number, Set<number>>()
  for (const note of track.notes) {
    const col = Math.round(note.startTime / SIXTEENTH)
    if (!drumHits.has(note.pitch)) drumHits.set(note.pitch, new Set())
    drumHits.get(note.pitch)!.add(col)
  }

  const activeRows = DRUM_ROWS.filter((row) => (drumHits.get(row.pitch)?.size ?? 0) > 0)
  const rows = activeRows.length > 0 ? activeRows : DRUM_ROWS.slice(3) // BD/SN/HH fallback

  const maxColRaw =
    track.notes.length > 0
      ? Math.ceil(Math.max(...track.notes.map((n) => n.startTime + n.duration)) / SIXTEENTH)
      : colsPerBar * 4
  const numBars = Math.ceil(maxColRaw / colsPerBar) + 1

  // Target ~60 content chars: each bar is colsPerBar + 1 ('|') chars
  const BARS_PER_ROW = Math.max(1, Math.floor(60 / (colsPerBar + 1)))

  const outputLines: string[] = [
    makeHeader(`${track.name} (Drums)`, bpm, timeSignature, 'Standard GM Percussion')
  ]

  for (let rowStart = 0; rowStart < numBars; rowStart += BARS_PER_ROW) {
    const rowEnd = Math.min(rowStart + BARS_PER_ROW, numBars)
    for (const row of rows) {
      const hits = drumHits.get(row.pitch) ?? new Set<number>()
      let line = `${row.label}|`
      for (let bar = rowStart; bar < rowEnd; bar++) {
        for (let beat = 0; beat < colsPerBar; beat++) {
          line += hits.has(bar * colsPerBar + beat) ? 'x' : '-'
        }
        line += '|'
      }
      outputLines.push(line)
    }
    outputLines.push('')
  }

  return outputLines.join('\n')
}

export function convertTracksToAsciiTab(
  tracks: ConvertedTrack[],
  bpm: number,
  timeSignature: { numerator: number; denominator: number }
): Array<{ filename: string; data: string }> {
  const results: Array<{ filename: string; data: string }> = []

  for (const track of tracks) {
    if (track.type === 'unknown') continue
    const content =
      track.type === 'drums'
        ? buildDrumTab(track, bpm, timeSignature)
        : buildInstrumentTab(track, bpm, timeSignature)
    results.push({ filename: `${track.safeName}.txt`, data: content })
  }

  return results
}
